Test Workflow

diff --git a/blih2github b/blih2github
--- a/blih2github
+++ b/blih2github
@@ -1,5 +1,14 @@
 #!/bin/bash
 
+## Push repo
+push() {
+	(git -C "$1" push origin master || git -C "$1" push origin main) 2> /dev/null > /dev/null
+}
+
+remove_origin() {
+	git -C "$1" remote remove origin 2> /dev/null > /dev/null;
+}
+
 ## Checks the number of argument is correct
 if [ "$#" -ne "4" ];
 then
@@ -26,26 +35,37 @@ do
 		continue
 	fi
 	repo_name=$(basename "$blih_dir")
+
+
 	echo "'$repo_name' is a Git Repository"
 	## Create repo in Github
 	echo "Creating '$repo_name' repository in '$GITHUB_ORGA'..."
-	curl -i -u "$GITHUB_UNAME:$GITHUB_ACCESSTOKEN" -X POST \
+	http_code=$(curl -i -u "$GITHUB_UNAME:$GITHUB_ACCESSTOKEN" -X POST \
 		-H "Accept: application/vnd.github.v3+json" "https://api.github.com/orgs/$GITHUB_ORGA/repos" \
-		-d "{\"name\":\"$repo_name\", \"visibility\": \"private\"}" > /dev/null 2> /dev/null
-	if [ "$?" -ne "0" ];
+		-d "{\"name\":\"$repo_name\", \"visibility\": \"private\"}" --write-out %{http_code} --silent --output curl_output.log)
+	if [[ "$http_code" != "201" ]];
 	then
-		echo "Oops.. Something went wrong with Github while creating the repository, moving on to the next one..."
-		continue
+		echo "Oops.. Something went wrong with Github while creating the repository... Here is what happened:"
+		cat curl_output.log ; rm curl_output.log
+		exit 1
 	fi
+	rm -f curl_output.log
+	# Waiting for the repository to be available
+	sleep 6
 	## adding remote to local repo
-	git -C "$blih_dir" remote remove origin;
-	## Push to remote
-	git -C "$blih_dir" remote add origin git@github.com:"$GITHUB_ORGA"/"$repo_name".git &&
-	(git -C "$blih_dir" push origin master || git -C "$blih_dir" push origin main) 2> /dev/null > /dev/null
-	if [ "$?" -ne "0" ];
+	remove_origin "$blih_dir"
+	## Push to remote via SSH
+	git -C "$blih_dir" remote add origin "git@github.com:$GITHUB_ORGA/$repo_name.git"
+	## If Push failed
+	if ! push "$blih_dir" ;
 	then
-		echo "Oops.. Something went wrong while pushing to remote, moving on to the next one..."
-		continue
+		## Push via http
+		git -C "$blih_dir" remote set-url origin "https://$GITHUB_ORGA:$GITHUB_ACCESSTOKEN@github.com/$GITHUB_ORGA/$repo_name"
+		if ! push "$blih_dir";
+		then
+			echo "Oops.. Something went wrong while pushing to remote"
+			exit 1
+		fi
 	fi
 	echo "Congrats! '$repo_name' is now available on github! check it out here: https://github.com/$GITHUB_ORGA/$repo_name."
 done
